# Generated by Django 4.0.4 on 2022-11-30 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('ProductId', models.AutoField(primary_key=True, serialize=False)),
                ('ProductName', models.CharField(max_length=500)),
                ('ProductAmount', models.IntegerField()),
                ('ProductPrice', models.IntegerField()),
                ('ProductTotalPrice', models.IntegerField()),
                ('Date', models.DateField()),
            ],
        ),
    ]
