# Generated by Django 4.0.4 on 2022-11-30 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpentApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ProductId',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
